### ISSUE TITLE
Enabling FALLBACK setting on `settings.py`

### ISSUE THREAD

**Issue by vionemc** [alecxe/scrapy-fake-useragent#14]
https://pypi.python.org/pypi/fake-useragent

There said

> You can completely disable ANY annoying exception with adding fallback: (version 0.1.4 added)
> ```
> import fake_useragent
> 
> ua = fake_useragent.UserAgent(fallback='Your favorite Browser')
> # in case if something went wrong, one more time it is REALLY!!! rare case
> ua.random == 'Your favorite Browser'
> ```

I want to use that fallback feature easily in Scrapy FakeUserAgent just by setting `FAKEUSERAGENT_FALLBACK` in `settings.py`

**Comment by alecxe** [comment]
@vionemc good idea! Thanks!
