### ISSUE TITLE
How to add to project?

### ISSUE THREAD

**Issue by brunomperes** [alecxe/scrapy-fake-useragent#15]
I'm a bit confused, I've never used setuptools, how do I add this to a scrapy project?

I've found this post (http://www.bertcarremans.be/avoiding-ip-banning-with-the-scrapy-framework/) but it doesn't seem the most up to date way of doing so.

Thanks!

**Comment by alecxe** [comment]
@brunomperes just install `scrapy-fake-useragent` with `pip`:

    pip install scrapy-fake-useragent

And then [configure your Scrapy settings to use the middleware](https://github.com/alecxe/scrapy-fake-useragent#configuration).

**Comment by alecxe** [comment]
Thanks for the PR.

**Comment by i-chaochen** [comment]
@alecxe what does it mean to turn off and add the new two middlewares?

```
Turn off the built-in UserAgentMiddleware and RetryMiddleware and add RandomUserAgentMiddleware and RetryUserAgentMiddleware.
```

After I installed it via pip and I have already added this following in my settings.py, but I still got ```Unhandled error in Deferred``` when I launched my spider. 

```
DOWNLOADER_MIDDLEWARES = {
    'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': None,
    'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware': 400,
    'scrapy_fake_useragent.middleware.RetryUserAgentMiddleware': 401,
}


FAKEUSERAGENT_PROVIDERS = [
    'scrapy_fake_useragent.providers.FakeUserAgentProvider',  # this is the first provider we'll try
    'scrapy_fake_useragent.providers.FakerProvider',  # if FakeUserAgentProvider fails, we'll use faker to generate a user-agent string for us
    'scrapy_fake_useragent.providers.FixedUserAgentProvider',  # fall back to USER_AGENT value
]

USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0'
```

Do I need to do anything in my middleware.py or import this scrapy-fake-useragent in my setting.py? And my scrapy version is 2.3.0

Thanks!
