### ISSUE TITLE
Didn't work when used to scrape linkedin

### ISSUE THREAD

**Issue by vionemc** [alecxe/scrapy-fake-useragent#2]
I set user-agent normally in scrapy, and I succeed to scrape linkedin.

I thought this library would help me bypass 999 response from linkedin even better, but I got 999 response like I used to.

**Comment by vionemc** [comment]
It seemed like it didn't change the user-agent at all

**Comment by vionemc** [comment]
I checked the user-agent used when running it. Instead of using a good and useful user-agent, it uses `['Scrapy/1.0.0rc1 (+http://scrapy.org)']`

**Comment by alecxe** [comment]
I think you might've just not followed the setup and configuration instructions. Most likely, the middleware was not enabled or the scrapy built-in middleware was not disabled.
