### ISSUE TITLE
Deprecated class warning on disabling UserAgentMiddleware

### ISSUE THREAD

**Issue by shafaq** [alecxe/scrapy-fake-useragent#3]
When using this line in settings.py, at running spider a warning for deprecated class is given.
`'scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware': None,`

Instead `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` should be used. Can you please change the docs to reflect this.

**Comment by alecxe** [comment]
Good point, updated the README. Thanks!
