### ISSUE TITLE
Merge scrapy-fake-useragent into fake-useragent

### ISSUE THREAD

**Issue by hellysmile** [alecxe/scrapy-fake-useragent#8]
Hey @alecxe!

I have proposal to merge our libs.

What do You think about it?

**Comment by alecxe** [comment]
@hellysmile Hi! I'm perfectly okay with it if you think this is something that should be a part of `fake-useragent`. 

We should probably have this middleware implemented inside `fake-useragent` and then I'll update the README and the PyPI page to point others to the fact that the middleware is now a part of `fake-useragent`. What do you think? Thanks.

**Comment by medse** [comment]
@hellysmile, @alecxe: Haven't come to any agreement? I think it's logical to have middleware within fake-useragent, not a big burden, but then we'll have everything under one roof.

**Comment by hellysmile** [comment]
Seems we are both ok, but someone need to do that...

**Comment by medse** [comment]
@hellysmile, do you need the project manager?:)
Looks like a trivial thing, and each of you has his own things to do. You cannot update the PyPI page for him, and he probably has no write access to your repo. Depends on how much time you have:)

**Comment by medse** [comment]
@alexce, can you make a PR to @hellysmile, merging the middleware there? I can then make the is_pc thing. Or you wanted to do it?

**Comment by JordanKadish** [comment]
Any further work being done here?

**Comment by alecxe** [comment]
Closing as it seems we are expanding capabilities a bit (#27) and it does not seem we can fit just fake-useragent.
